### ISSUE TITLE
push pod 1.0.1

### ISSUE THREAD

**Issue by billyto** [cwimberger/ctfuzzysearch#3]
Would you mind to push v1.0.1 to the Cocoapods trunk?

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

Thanks,

**Comment by billyto** [comment]
Hi Christoph, 
If you are short on time to go thru the docs, this is what we need to run:

```
pod trunk push CTFuzzySearch.podspec
```

Or I can run it if you add me as contributor to the trunk with:

```
pod trunk add-owner CTFuzzySearch billy.tobon@gmail.com
```

Cheers,

**Comment by cwimberger** [comment]
Hi Billy,
I had to setup cocoapods again, but now 1.0.1 has been pushed!

```
- Log messages:
- March 8th, 06:08: Push for `CTFuzzySearch 1.0.1' initiated.
- March 8th, 06:08: Push for `CTFuzzySearch 1.0.1' has been pushed (2.127013628 s).
```

Cheers
